# CircleCI build for https://circleci.com/gh/monicahq/centralperk

aliases:
  - &docker_build
    run:
      name: Build docker image
      command: make docker_build
  - &docker_images
    run:
      name: List docker image
      command: docker images
  - &docker_login
    run:
      name: Login to docker
      command: echo $DOCKER_LOGIN | docker login -u $DOCKER_USER --password-stdin  
  - &docker_push
    run:
      name: Publish docker image
      command: make docker_push
  - &docker_push_master
    run:
      name: Publish docker image
      command: make docker_push_master 

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - *docker_build
      - *docker_images
      - *docker_login
      - *docker_push

  build-master:
    machine: true
    steps:
      - checkout
      - *docker_build
      - *docker_images
      - *docker_login
      - *docker_push_master
      - run:
          name: Notify microbadger
          command: |
            # notify microbadger to update
            # https://microbadger.com/images/monicahq/circleci-docker-centralperk
            curl -X POST $MICROBADGER_WEBHOOK

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      - build-master:
          filters:
            branches:
              only:
                - master
                - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
